import type {
  User, Lead, Homeowner, InsurancePolicy, Claim, Inspection,
  ContingencyAgreement, Campaign, Activity, StormEvent
} from '@/types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Marcus Johnson',
    email: 'marcus@stormshieldroofing.com',
    role: 'manager',
    phone: '(555) 100-0001',
  },
  {
    id: 'user-2',
    name: 'Jake Rodriguez',
    email: 'jake@stormshieldroofing.com',
    role: 'sales_rep',
    phone: '(555) 100-0002',
  },
  {
    id: 'user-3',
    name: 'Sarah Mitchell',
    email: 'sarah@stormshieldroofing.com',
    role: 'sales_rep',
    phone: '(555) 100-0003',
  },
  {
    id: 'user-4',
    name: 'Devon Williams',
    email: 'devon@stormshieldroofing.com',
    role: 'sales_rep',
    phone: '(555) 100-0004',
  },
];

export const mockHomeowners: Homeowner[] = [
  {
    id: 'ho-1',
    firstName: 'Robert',
    lastName: 'Thompson',
    email: 'robert.thompson@email.com',
    phone: '(555) 200-0001',
    address: '1234 Oak Ridge Dr',
    city: 'Dallas',
    state: 'TX',
    zip: '75201',
    propertyType: 'residential',
    createdAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'ho-2',
    firstName: 'Maria',
    lastName: 'Garcia',
    email: 'maria.garcia@email.com',
    phone: '(555) 200-0002',
    address: '5678 Elm Street',
    city: 'Fort Worth',
    state: 'TX',
    zip: '76102',
    propertyType: 'residential',
    createdAt: '2026-03-18T14:00:00Z',
  },
  {
    id: 'ho-3',
    firstName: 'James',
    lastName: 'Wilson',
    email: 'james.wilson@email.com',
    phone: '(555) 200-0003',
    address: '9012 Maple Ave',
    city: 'Plano',
    state: 'TX',
    zip: '75023',
    propertyType: 'residential',
    createdAt: '2026-03-20T09:00:00Z',
  },
  {
    id: 'ho-4',
    firstName: 'Linda',
    lastName: 'Martinez',
    email: 'linda.martinez@email.com',
    phone: '(555) 200-0004',
    address: '3456 Cedar Blvd',
    city: 'Arlington',
    state: 'TX',
    zip: '76010',
    propertyType: 'residential',
    createdAt: '2026-03-22T11:00:00Z',
  },
  {
    id: 'ho-5',
    firstName: 'David',
    lastName: 'Brown',
    email: 'david.brown@email.com',
    phone: '(555) 200-0005',
    address: '7890 Pine Ct',
    city: 'McKinney',
    state: 'TX',
    zip: '75069',
    propertyType: 'residential',
    createdAt: '2026-03-25T08:00:00Z',
  },
  {
    id: 'ho-6',
    firstName: 'Patricia',
    lastName: 'Davis',
    email: 'patricia.davis@email.com',
    phone: '(555) 200-0006',
    address: '2345 Birch Ln',
    city: 'Frisco',
    state: 'TX',
    zip: '75034',
    propertyType: 'residential',
    createdAt: '2026-03-27T16:00:00Z',
  },
];

export const mockPolicies: InsurancePolicy[] = [
  {
    id: 'pol-1',
    homeownerId: 'ho-1',
    leadId: 'lead-1',
    carrier: 'State Farm',
    policyNumber: 'SF-2025-88412',
    policyType: 'RCV',
    deductible: 2500,
    deductibleType: 'flat',
    effectiveDate: '2025-06-01',
    expirationDate: '2026-06-01',
    bestDateOfLoss: '2026-03-12',
    dwellingCoverage: 350000,
    otherStructuresCoverage: 35000,
    personalPropertyCoverage: 175000,
    lossOfUseCoverage: 70000,
    hasWindCoverage: true,
    hasHailCoverage: true,
    uploadedAt: '2026-03-16T10:00:00Z',
    analyzedAt: '2026-03-16T10:01:00Z',
  },
  {
    id: 'pol-2',
    homeownerId: 'ho-2',
    leadId: 'lead-2',
    carrier: 'Allstate',
    policyNumber: 'AS-2025-55123',
    policyType: 'ACV',
    deductible: 1,
    deductibleType: 'percentage',
    effectiveDate: '2025-09-15',
    expirationDate: '2026-09-15',
    bestDateOfLoss: '2026-03-12',
    dwellingCoverage: 280000,
    otherStructuresCoverage: 28000,
    personalPropertyCoverage: 140000,
    lossOfUseCoverage: 56000,
    windHailDeductible: 5600,
    hasWindCoverage: true,
    hasHailCoverage: true,
    uploadedAt: '2026-03-19T14:00:00Z',
    analyzedAt: '2026-03-19T14:01:00Z',
  },
  {
    id: 'pol-3',
    homeownerId: 'ho-3',
    leadId: 'lead-3',
    carrier: 'USAA',
    policyNumber: 'USAA-2025-77234',
    policyType: 'RCV',
    deductible: 3000,
    deductibleType: 'flat',
    effectiveDate: '2025-04-01',
    expirationDate: '2026-04-01',
    bestDateOfLoss: '2026-02-28',
    dwellingCoverage: 425000,
    otherStructuresCoverage: 42500,
    personalPropertyCoverage: 212500,
    lossOfUseCoverage: 85000,
    hasWindCoverage: true,
    hasHailCoverage: true,
    uploadedAt: '2026-03-21T09:00:00Z',
    analyzedAt: '2026-03-21T09:01:00Z',
  },
];

export const mockStormEvents: StormEvent[] = [
  {
    id: 'storm-1',
    date: '2026-03-12',
    type: 'hail',
    severity: 'severe',
    location: 'Dallas-Fort Worth Metroplex',
    zipCodes: ['75201', '76102', '75023', '76010', '75069', '75034'],
    hailSize: '1.75 inch',
    description: 'Severe hailstorm with quarter to golf ball sized hail across DFW metroplex. Widespread roof damage reported.',
    source: 'NOAA Storm Events Database',
  },
  {
    id: 'storm-2',
    date: '2026-02-28',
    type: 'wind',
    severity: 'moderate',
    location: 'North Texas Region',
    zipCodes: ['75023', '75069', '75034'],
    windSpeed: '65 mph',
    description: 'Strong straight-line winds with gusts up to 65mph causing shingle and fascia damage.',
    source: 'NOAA Storm Events Database',
  },
  {
    id: 'storm-3',
    date: '2026-01-15',
    type: 'hail_and_wind',
    severity: 'severe',
    location: 'Collin County, TX',
    zipCodes: ['75023', '75069'],
    hailSize: '2.0 inch',
    windSpeed: '70 mph',
    description: 'Supercell thunderstorm producing large hail and damaging winds. Significant structural damage.',
    source: 'NOAA Storm Events Database',
  },
  {
    id: 'storm-4',
    date: '2025-11-20',
    type: 'hail',
    severity: 'moderate',
    location: 'Tarrant County, TX',
    zipCodes: ['76102', '76010'],
    hailSize: '1.25 inch',
    description: 'Moderate hailstorm with nickel to quarter sized hail. Cosmetic and functional damage to roofing materials.',
    source: 'NOAA Storm Events Database',
  },
];

export const mockLeads: Lead[] = [
  {
    id: 'lead-1',
    homeownerId: 'ho-1',
    assignedTo: 'user-2',
    jobType: 'insurance',
    status: 'claim_filed',
    source: 'door_knock',
    notes: 'Significant hail damage on south-facing slope. Homeowner very interested.',
    createdAt: '2026-03-15T10:00:00Z',
    updatedAt: '2026-03-28T10:00:00Z',
    inspectionDate: '2026-03-17T14:00:00Z',
    policyId: 'pol-1',
    claimId: 'claim-1',
    contingencyId: 'cont-1',
    estimatedValue: 18500,
  },
  {
    id: 'lead-2',
    homeownerId: 'ho-2',
    assignedTo: 'user-3',
    jobType: 'insurance',
    status: 'contingency_sent',
    source: 'referral',
    notes: 'Referred by Robert Thompson. ACV policy - need to discuss depreciation.',
    createdAt: '2026-03-18T14:00:00Z',
    updatedAt: '2026-03-30T14:00:00Z',
    inspectionDate: '2026-03-20T10:00:00Z',
    policyId: 'pol-2',
    estimatedValue: 14200,
  },
  {
    id: 'lead-3',
    homeownerId: 'ho-3',
    assignedTo: 'user-2',
    jobType: 'insurance',
    status: 'inspection_complete',
    source: 'storm_chaser',
    notes: 'Wind damage primarily on ridge caps and north side.',
    createdAt: '2026-03-20T09:00:00Z',
    updatedAt: '2026-03-26T09:00:00Z',
    inspectionDate: '2026-03-22T11:00:00Z',
    policyId: 'pol-3',
    estimatedValue: 22000,
  },
  {
    id: 'lead-4',
    homeownerId: 'ho-4',
    assignedTo: 'user-4',
    jobType: 'insurance',
    status: 'inspection_scheduled',
    source: 'website',
    notes: 'Homeowner found us online. Reports leaking in master bedroom after last storm.',
    createdAt: '2026-03-22T11:00:00Z',
    updatedAt: '2026-03-22T11:00:00Z',
    inspectionDate: '2026-04-05T09:00:00Z',
    estimatedValue: 16000,
  },
  {
    id: 'lead-5',
    homeownerId: 'ho-5',
    assignedTo: 'user-3',
    jobType: 'retail',
    status: 'retail_estimate_sent',
    source: 'website',
    notes: 'Roof is 20+ years old, wants full replacement. No storm damage.',
    createdAt: '2026-03-25T08:00:00Z',
    updatedAt: '2026-03-28T08:00:00Z',
    estimatedValue: 12500,
  },
  {
    id: 'lead-6',
    homeownerId: 'ho-6',
    assignedTo: 'user-2',
    jobType: 'insurance',
    status: 'new',
    source: 'door_knock',
    notes: 'New lead from door knocking in Frisco after March 12 storm.',
    createdAt: '2026-03-27T16:00:00Z',
    updatedAt: '2026-03-27T16:00:00Z',
    estimatedValue: 20000,
  },
];

export const mockClaims: Claim[] = [
  {
    id: 'claim-1',
    leadId: 'lead-1',
    homeownerId: 'ho-1',
    policyId: 'pol-1',
    claimNumber: 'CLM-2026-001234',
    carrier: 'State Farm',
    adjusterName: 'Mike Anderson',
    adjusterEmail: 'mike.anderson@statefarm.com',
    adjusterPhone: '(555) 300-0001',
    status: 'adjuster_assigned',
    claimType: 'hail',
    dateOfLoss: '2026-03-12',
    dateFiled: '2026-03-20',
    followUps: [
      {
        id: 'fu-1',
        claimId: 'claim-1',
        type: 'email',
        sentAt: '2026-03-25T10:00:00Z',
        sentTo: 'mike.anderson@statefarm.com',
        subject: 'Follow Up - Claim CLM-2026-001234 - Thompson Residence',
        body: 'Dear Mr. Anderson,\n\nI am writing to follow up on claim CLM-2026-001234 for the Thompson residence at 1234 Oak Ridge Dr, Dallas, TX 75201.\n\nPlease let us know the status of adjuster assignment and when we can expect the inspection.\n\nBest regards,\nStormShield Roofing',
        status: 'read',
      },
    ],
    notes: 'Adjuster Mike Anderson assigned. Waiting for inspection date.',
    createdAt: '2026-03-20T10:00:00Z',
    updatedAt: '2026-03-28T10:00:00Z',
  },
];

export const mockInspections: Inspection[] = [
  {
    id: 'insp-1',
    leadId: 'lead-1',
    homeownerId: 'ho-1',
    scheduledDate: '2026-03-17T14:00:00Z',
    completedDate: '2026-03-17T15:30:00Z',
    photos: [
      { id: 'photo-1', url: '/placeholder-roof-1.jpg', caption: 'South-facing slope overview', category: 'overview', takenAt: '2026-03-17T14:15:00Z' },
      { id: 'photo-2', url: '/placeholder-roof-2.jpg', caption: 'Hail impact marks on shingles', category: 'damage', takenAt: '2026-03-17T14:25:00Z' },
      { id: 'photo-3', url: '/placeholder-roof-3.jpg', caption: 'Damaged ridge cap', category: 'damage', takenAt: '2026-03-17T14:35:00Z' },
    ],
    notes: 'Significant hail damage across south and west facing slopes. Multiple shingle cracks and bruising.',
    findings: '47 hail hits per 10x10 test square on south slope. Ridge caps cracked. Gutters dented.',
    damageType: 'hail',
    damageSeverity: 'severe',
    status: 'report_generated',
  },
  {
    id: 'insp-2',
    leadId: 'lead-3',
    homeownerId: 'ho-3',
    scheduledDate: '2026-03-22T11:00:00Z',
    completedDate: '2026-03-22T12:00:00Z',
    photos: [
      { id: 'photo-4', url: '/placeholder-roof-4.jpg', caption: 'North side overview', category: 'overview', takenAt: '2026-03-22T11:10:00Z' },
      { id: 'photo-5', url: '/placeholder-roof-5.jpg', caption: 'Lifted shingles from wind', category: 'damage', takenAt: '2026-03-22T11:20:00Z' },
    ],
    notes: 'Wind damage on ridge and north-facing slope. Several shingles lifted and torn.',
    findings: 'Ridge caps lifted on 60% of ridge line. 12 shingles completely missing on north slope.',
    damageType: 'wind',
    damageSeverity: 'moderate',
    status: 'completed',
  },
  {
    id: 'insp-3',
    leadId: 'lead-4',
    homeownerId: 'ho-4',
    scheduledDate: '2026-04-05T09:00:00Z',
    photos: [],
    notes: 'Scheduled for April 5th. Homeowner reports interior leaks.',
    findings: '',
    status: 'scheduled',
  },
];

export const mockContingencies: ContingencyAgreement[] = [
  {
    id: 'cont-1',
    leadId: 'lead-1',
    homeownerId: 'ho-1',
    policyId: 'pol-1',
    homeownerName: 'Robert Thompson',
    homeownerAddress: '1234 Oak Ridge Dr',
    homeownerCity: 'Dallas',
    homeownerState: 'TX',
    homeownerZip: '75201',
    homeownerPhone: '(555) 200-0001',
    homeownerEmail: 'robert.thompson@email.com',
    insuranceCarrier: 'State Farm',
    policyNumber: 'SF-2025-88412',
    policyType: 'RCV',
    deductible: 2500,
    dateOfLoss: '2026-03-12',
    claimType: 'hail',
    hasInteriorLeaks: false,
    isHailOrWindClaim: 'hail',
    hasOutsideStructures: false,
    adminNotes: 'Priority job - good referral source potential',
    salesRepId: 'user-2',
    salesRepName: 'Jake Rodriguez',
    status: 'signed',
    generatedAt: '2026-03-18T10:00:00Z',
    sentAt: '2026-03-18T10:30:00Z',
    signedAt: '2026-03-18T14:00:00Z',
    docusignEnvelopeId: 'ds-env-001',
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: 'camp-1',
    name: 'March Storm Door Knocking',
    type: 'door_knock',
    status: 'active',
    budget: 5000,
    spent: 2100,
    leadsGenerated: 12,
    startDate: '2026-03-13',
    targetArea: 'Dallas-Fort Worth',
    targetZipCodes: ['75201', '76102', '75023'],
    description: 'Post-storm door knocking campaign targeting areas hit by March 12 hailstorm.',
    createdBy: 'user-1',
  },
  {
    id: 'camp-2',
    name: 'Spring Digital Ad Campaign',
    type: 'digital_ad',
    status: 'active',
    budget: 3000,
    spent: 1800,
    leadsGenerated: 8,
    startDate: '2026-03-01',
    endDate: '2026-05-31',
    description: 'Google Ads and Facebook targeting homeowners in storm-affected areas.',
    createdBy: 'user-1',
  },
  {
    id: 'camp-3',
    name: 'Customer Referral Program',
    type: 'referral_program',
    status: 'active',
    budget: 10000,
    spent: 1500,
    leadsGenerated: 5,
    startDate: '2026-01-01',
    description: '$250 referral bonus for completed jobs. Ongoing program.',
    createdBy: 'user-1',
  },
];

export const mockActivities: Activity[] = [
  {
    id: 'act-1',
    leadId: 'lead-1',
    userId: 'user-2',
    type: 'status_change',
    description: 'Status changed to Claim Filed',
    createdAt: '2026-03-28T10:00:00Z',
  },
  {
    id: 'act-2',
    leadId: 'lead-1',
    claimId: 'claim-1',
    userId: 'user-2',
    type: 'email',
    description: 'Follow-up email sent to adjuster Mike Anderson',
    createdAt: '2026-03-25T10:00:00Z',
  },
  {
    id: 'act-3',
    leadId: 'lead-2',
    userId: 'user-3',
    type: 'document',
    description: 'Contingency agreement sent to Maria Garcia via DocuSign',
    createdAt: '2026-03-30T14:00:00Z',
  },
  {
    id: 'act-4',
    leadId: 'lead-3',
    userId: 'user-2',
    type: 'inspection',
    description: 'Inspection completed - wind damage found on north slope',
    createdAt: '2026-03-22T12:00:00Z',
  },
  {
    id: 'act-5',
    leadId: 'lead-4',
    userId: 'user-4',
    type: 'note',
    description: 'Inspection scheduled for April 5th. Homeowner has interior leaks.',
    createdAt: '2026-03-22T11:00:00Z',
  },
  {
    id: 'act-6',
    leadId: 'lead-6',
    userId: 'user-2',
    type: 'note',
    description: 'New lead from door knocking in Frisco neighborhood',
    createdAt: '2026-03-27T16:00:00Z',
  },
  {
    id: 'act-7',
    leadId: 'lead-1',
    userId: 'user-2',
    type: 'text',
    description: 'Sent inspection report follow-up text to Robert Thompson',
    createdAt: '2026-03-18T09:00:00Z',
  },
];
